Paginate = 4
baseURL = "/"
languageCode = "en-us"
theme = "kube"
title = "Site Shakeup"
[[menu.main]]
name = "Faq"
url = "/faq/"
weight = -100
[[menu.main]]
name = "Contact"
url = "/contact-us/"
weight = -100
[[menu.main]]
name = "About"
url = "/about/"
weight = -100
[params]
author = "Site Shakeup"
description = "Accounting websites that get clients."
email = "contact@siteshakeup.com"
github = ""
rsslink = "/index.xml"
twitter = ""
